# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: docs/conf.py

formats: [htmlzip, pdf, epub]

python:
   install:
   - requirements: docs/sphinx/requirements.txt

conda:
   environment: docs/environment.yml # needed until ubuntu ships doxygen >= 1.9.8

build:
   os: ubuntu-20.04
   tools:
      python: "mambaforge-22.9" # needed until ubuntu ships doxygen >= 1.9.8
   apt_packages:
     - "gfortran" # For pre-processing fortran sources
     - "graphviz" # For dot graphs in doxygen
