# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: docs/conf.py

formats: []

python:
   install:
   - requirements: docs/sphinx/requirements.txt

build:
   os: ubuntu-22.04
   tools:
      python: "3.10"
   apt_packages:
     - "doxygen"
     - "gfortran" # For pre-processing fortran sources
     - "graphviz" # For dot graphs in doxygen
   jobs:
     post_checkout:
       - if [ -d ../llvm-project ]; then rm -rf ../llvm-project; fi
       - if [ -d ../clr ]; then rm -rf ../clr; fi
       - if [ -d ../ROCR-Runtime ]; then rm -rf ../ROCR-Runtime; fi
       - git clone --depth=1 --single-branch --branch rocdoc-195 https://github.com/StreamHPC/llvm-project.git ../llvm-project
       - git clone --depth=1 --single-branch --branch docs/develop    https://github.com/ROCm/clr.git ../clr
       - git clone --depth=1 --single-branch --branch master     https://github.com/ROCm/ROCR-Runtime.git ../ROCR-Runtime
     post_build:
       - rm -rf ../clr
       - rm -rf ../llvm-project
       - rm -rf ../ROCR-Runtime
