// Auto-generated by cmake

#ifndef HIP_VERSION_H
#define HIP_VERSION_H

#define HIP_VERSION_MAJOR 1
#define HIP_VERSION_MINOR 5
#define HIP_VERSION_PATCH 20033
#define HIP_VERSION       (HIP_VERSION_MAJOR * 100 + HIP_VERSION_MINOR)

#endif

